name: Sync upstream template

on:
  schedule:
    - cron: "0 3 * * 2"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: template-sync
  cancel-in-progress: false

jobs:
  template-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - name: Sync upstream template
        uses: AndreasAugustin/actions-template-sync@8a0f668b83c32a0f673353086d74f12b8853d4f5 # v2
        with:
          source_gh_token: ${{ github.token }}
          target_gh_token: ${{ github.token }}
          source_repo_path: NeverMorewd/DotNetPerformanceDashboard
          upstream_branch: main
          pr_branch_name_prefix: chore/template-sync
          pr_title: "Sync changes from dashboard template"
          pr_commit_msg: "chore: sync dashboard template"
